# Generated by Django 4.2.11 on 2025-10-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appArtems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID места'),
        ),
    ]
