# Generated by Django 4.2.11 on 2025-10-24 17:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appArtems', '0002_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
